### ISSUE TITLE
Snapshot issues report #2

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/MiniPhysics-By-38A#2]
1. Debug information appear glitchy.

![debug_1](https://cloud.githubusercontent.com/assets/7596025/17087315/d1bf2adc-520f-11e6-9dc4-7c5ee4fa0377.png)
2. Also character velocity info is missing.
3. Walking up one slope causes character to walk straight into another one.

![slope_walk1](https://cloud.githubusercontent.com/assets/7596025/17087331/1b023e8c-5210-11e6-9661-b73200ef7adf.png)
![slope_walk2](https://cloud.githubusercontent.com/assets/7596025/17087332/1d2580d4-5210-11e6-80c7-ced944552ca5.png)
4. Jittering of ground detection when standing on slope top without any additional support.

![jitter1](https://cloud.githubusercontent.com/assets/7596025/17087345/4314a5f4-5210-11e6-8ef5-51dbb22935c9.png)
![jitter2](https://cloud.githubusercontent.com/assets/7596025/17087346/45b91cf4-5210-11e6-81f3-b37b2c3c0f12.png)
5. False cliff detection when going down slope.

![false_slope_cliff](https://cloud.githubusercontent.com/assets/7596025/17087378/1d8ff670-5211-11e6-89c9-5f47249f7e25.png)

**Comment by Wohlstand** [comment]
1. Because I wasn't cared about coordinates of labels yet EDIT: Oh, when I came to job and I see from monitor, not from phone, Now I see that font is buggy :stuck_out_tongue_winking_eye: 
2. I disabled printing of it, because no more needed, but I can enable it back
3. That already planned to fix in todo: a "between floor and ceiling" trouble.
4. That one thing still not be fixed after fixing of jittering on slope surface
5. Wasn't completely done, this is last thing to fix to take accurate cliff detection

**Comment by Alucard648** [comment]
Also apparently walking horizontally from one block to another resets horizontal velocity. This is why mid-air movement seems faster.

**Comment by Wohlstand** [comment]
Wired that debug info printed at you so wired, mayby a some bug in the fonts at you? I'll try to set Courier New font. At me font printing works fine
![2016-07-25_12-00-56](https://cloud.githubusercontent.com/assets/6751442/17095957/c3701a4a-525f-11e6-9f05-0d29176727e8.png)

**Comment by Alucard648** [comment]
For me, it looks like this:
![too_fat](https://cloud.githubusercontent.com/assets/7596025/17098973/08636130-526e-11e6-95f8-c085c3d3ff60.png)
Windows 7 sp1.
Also the same pic shows new issue from newest snapshot: since you expanded character size, he sometimes fall into one-block wide holes, sometimes refuses to do that at all.
Another issue with slopes: on rare occassion when walking down slope, vertical velocity resets to 0, which causes character to "bump" off slope.

**Comment by Wohlstand** [comment]
That wired, because at job I have same Windows 7 sp1.
About stumbling at rectangular block's corners, that I saw too, so, trying to fix that

**Comment by Wohlstand** [comment]
EDIT: Just found that corner stumbling effect causes zeroing of Y velocity on coming to bottom of the slope :stuck_out_tongue_winking_eye:  I think, I have idea how to fix, will try that

**Comment by Wohlstand** [comment]
All of those troubles are been resolved, I'll upload new snapshot bit later. Alone task I have - improve accuracy of cliff detection and don't hit crusiging cellings or while stucking between slope and selling

**Comment by Alucard648** [comment]
Will it be possible to have things like:
1. Half-Solid platforms and slopes/stairs.
2. Gravity flipping.
3. Pushable NPC`s, including being able to push massive stacks of NPC`s under certain conditions.
4. \* Advanced 360 degree slope movement physics for Sonic the Hedgehog-like games.

**Comment by Wohlstand** [comment]
1) yes, that very important
2) That is not hard, while collusions are working fine
3) that is not hard to, just using another collision solving formula for pushable npcs
4) that is not so easy to have physics with rotation of elements, and need to use very another formulas for collision processing which is not compatible with current physics

**Comment by Wohlstand** [comment]
Okay, those bugs are been fixed. If you wish keep new suggestions, please in new issue
