### ISSUE TITLE
Character phases trough solid floor on hitting sloped ceiling.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/MiniPhysics-By-38A#3]
Screenshot says all:
![perma_stuck](https://cloud.githubusercontent.com/assets/7596025/17218430/6d169abe-54f0-11e6-9611-365dbea2deba.png)
Tested on latest snapshot.

**Comment by Wohlstand** [comment]
This has been fixed: now impossible to walk into so low ceiling, character will be blocked, and alone way - turn and go backward
